// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAH4BCj-96FeftYEmnr0pm2eAw5vcZi50',
    appId: '1:432686352149:web:091e1d00c33ffeb7320b1c',
    messagingSenderId: '432686352149',
    projectId: 'preparationhotspot-92b87',
    authDomain: 'preparationhotspot-92b87.firebaseapp.com',
    storageBucket: 'preparationhotspot-92b87.firebasestorage.app',
    measurementId: 'G-7Z579H0SDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5YZVtk5cEQolNy7ZpTtiLY2aMhknqL7g',
    appId: '1:432686352149:android:1155be17fa0da845320b1c',
    messagingSenderId: '432686352149',
    projectId: 'preparationhotspot-92b87',
    storageBucket: 'preparationhotspot-92b87.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3joRnvT1pjA9Z2jsRLHzKYN73RBT_eqE',
    appId: '1:432686352149:ios:9eef8149790f7a1c320b1c',
    messagingSenderId: '432686352149',
    projectId: 'preparationhotspot-92b87',
    storageBucket: 'preparationhotspot-92b87.firebasestorage.app',
    androidClientId: '432686352149-c6qup10c7dpi6l906obt8u3dg83bauv7.apps.googleusercontent.com',
    iosClientId: '432686352149-4613169j38n6npikhqah4dnu5jtu0g1p.apps.googleusercontent.com',
    iosBundleId: 'com.preparationhotspot.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3joRnvT1pjA9Z2jsRLHzKYN73RBT_eqE',
    appId: '1:432686352149:ios:458a896a3bd20a12320b1c',
    messagingSenderId: '432686352149',
    projectId: 'preparationhotspot-92b87',
    storageBucket: 'preparationhotspot-92b87.firebasestorage.app',
    androidClientId: '432686352149-c6qup10c7dpi6l906obt8u3dg83bauv7.apps.googleusercontent.com',
    iosClientId: '432686352149-9tg6pelen3o5h3tr9p9flmq781d92jii.apps.googleusercontent.com',
    iosBundleId: 'com.example.preparationhotspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAH4BCj-96FeftYEmnr0pm2eAw5vcZi50',
    appId: '1:432686352149:web:7233c90535102709320b1c',
    messagingSenderId: '432686352149',
    projectId: 'preparationhotspot-92b87',
    authDomain: 'preparationhotspot-92b87.firebaseapp.com',
    storageBucket: 'preparationhotspot-92b87.firebasestorage.app',
    measurementId: 'G-5C3B6LFVZK',
  );
}
